import * as XLSX from 'xlsx';
import Papa from 'papaparse';
import { CANONICAL_SCHEMA } from '../data/canonicalSchema.js';
import { formatDate } from '../utils/id.js';

function confidenceLabel(m) {
  if (!m) return '—';
  if (m.matchedBy === 'manual') return 'High (manual)';
  if (m.score >= 0.9) return `High (${m.score.toFixed(2)})`;
  return `Medium (${m.score.toFixed(2)})`;
}

function specRows(type, results) {
  const attrs = CANONICAL_SCHEMA[type];
  const header = ['Canonical Attribute'];
  for (const { upload } of results) {
    header.push(`${upload.vendor} Field`, 'Confidence', 'Matched By');
  }
  const rows = [header];
  for (const attr of attrs) {
    const row = [attr.label];
    for (const { effective } of results) {
      const m = effective.byAttr[attr.id];
      row.push(m ? m.field : '—', confidenceLabel(m), m ? m.matchedBy : '—');
    }
    rows.push(row);
  }
  return rows;
}

/** results: [{ upload, effective }] as computed by matchFile per selected upload. */
export function buildWorkbook(type, results, generatedBy) {
  const wb = XLSX.utils.book_new();
  const today = new Date().toISOString().slice(0, 10);

  // Sheet 1: Summary
  const summary = [
    ['SRM Attribute Crosswalk — Mapping Specification'],
    ['Beacon Advisory Partners'],
    [],
    ['Data Type', type],
    ['Generated', today],
    ['Generated By', generatedBy || ''],
    [],
    ['Vendor', 'File', 'Uploaded', 'Fields in File', 'Attributes Mapped', 'Coverage %'],
    ...results.map(({ upload, effective }) => [
      upload.vendor,
      upload.fileName,
      formatDate(upload.uploadedAt),
      effective.stats.totalFields,
      `${effective.stats.mapped} / ${effective.stats.totalAttrs}`,
      effective.stats.coveragePct,
    ]),
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summary);
  wsSummary['!cols'] = [{ wch: 22 }, { wch: 32 }, { wch: 14 }, { wch: 14 }, { wch: 18 }, { wch: 12 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // Sheet 2: Mapping Spec
  const spec = specRows(type, results);
  const wsSpec = XLSX.utils.aoa_to_sheet(spec);
  wsSpec['!cols'] = [{ wch: 26 }, ...results.flatMap(() => [{ wch: 26 }, { wch: 16 }, { wch: 12 }])];
  XLSX.utils.book_append_sheet(wb, wsSpec, 'Mapping Spec');

  // Sheet 3: Unmapped Fields
  const unmapped = [['Vendor', 'File', 'Unmapped Field', 'Sample Value']];
  for (const { upload, effective } of results) {
    for (const h of effective.unmappedHeaders) {
      unmapped.push([
        upload.vendor,
        upload.fileName,
        h,
        (upload.samplesByHeader[h] || [])[0] || '',
      ]);
    }
  }
  const wsUnmapped = XLSX.utils.aoa_to_sheet(unmapped);
  wsUnmapped['!cols'] = [{ wch: 14 }, { wch: 32 }, { wch: 28 }, { wch: 28 }];
  XLSX.utils.book_append_sheet(wb, wsUnmapped, 'Unmapped Fields');

  return { wb, fileName: `SRM-Crosswalk_${type}_${today}.xlsx` };
}

export function downloadXlsx(type, results, generatedBy) {
  const { wb, fileName } = buildWorkbook(type, results, generatedBy);
  XLSX.writeFile(wb, fileName);
}

export function downloadCsv(type, results) {
  const csv = Papa.unparse(specRows(type, results));
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `SRM-Crosswalk_${type}_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
